stages:
  preprocess:
    cmd: python src/data/work_dataset.py
    deps:
    - data/raw/life_expectancy_data.csv
    - src/data/work_dataset.py
    params:
    - config/parameters.yaml:
      - base
      - data
    outs:
    - data/EDA_processed/data_x.npy
    - data/EDA_processed/data_y.npy
    - data/EDA_processed/life_expectancy_data_processed.csv
    - data/EDA_processed/test_data.csv
    - data/EDA_processed/train_data.csv

  LinearRegression:
    cmd: python src/models/LinearRegression.py
    deps:
    - data/EDA_processed/train_data.csv
    - src/models/LinearRegression.py
    params:
    - config/parameters.yaml:
      - base
      - models.LinearRegression
    outs:
    - models/LinearRegression.pkl
    - reports/LinearRegression_coeff.json
    - reports/images/LinearRegression_coefficients.png

  DecisionTree:
    cmd: python src/models/DecisionTree.py
    deps:
    - data/EDA_processed/train_data.csv
    - src/models/DecisionTree.py
    params:
    - config/parameters.yaml:
      - base
      - models.DecisionTree
    outs:
    - models/DecisionTree.pkl
    - reports/images/DecisionTree_structure.png

  CatBoost:
    cmd: python src/models/CatBoost.py
    deps:
    - data/EDA_processed/train_data.csv
    - src/models/CatBoost.py
    params:
    - config/parameters.yaml:
      - base
      - models.CatBoost
    outs:
    - models/CatBoost.cbm
    - reports/images/CatBoost_feature_importance.png

  XGBoost:
    cmd: python src/models/XGBoost.py
    deps:
    - data/EDA_processed/train_data.csv
    - src/models/XGBoost.py
    params:
    - config/parameters.yaml:
      - base
      - models.XGBoost
    outs:
    - models/XGBoost.json
    - reports/images/XGBoost_feature_importance.png

  DenseNeuralNetwork:
    cmd: python src/models/DenseNeuralNetwork.py
    deps:
    - data/EDA_processed/train_data.csv
    - src/models/DenseNeuralNetwork.py
    params:
    - config/parameters.yaml:
      - base
      - models.DenseNeuralNetwork
    outs:
    - models/DenseNeuralNetwork.keras
    - reports/images/DenseNeuralNetwork_loss_curve.png
    - reports/images/DenseNeuralNetwork_model_graph.png
    - reports/images/DenseNeuralNetwork_weights_layer_1.png
    - reports/images/DenseNeuralNetwork_weights_layer_2.png
    - reports/images/DenseNeuralNetwork_weights_layer_3.png
    - reports/images/DenseNeuralNetwork_weights_layer_4.png

  test_LinearRegression:
    cmd: python src/test_models/test_LR.py
    deps:
    - data/EDA_processed/test_data.csv
    - models/LinearRegression.pkl
    - src/test_models/test_LR.py
    params:
    - config/parameters.yaml:
      - base
      - models.LinearRegression
    metrics:
    - dvclive/LinearRegression/metrics.json
    plots:
    - dvclive/LinearRegression/plots

  test_DecisionTree:
    cmd: python src/test_models/test_DT.py
    deps:
    - data/EDA_processed/test_data.csv
    - models/DecisionTree.pkl
    - src/test_models/test_DT.py
    params:
    - config/parameters.yaml:
      - base
      - models.DecisionTree
    metrics:
    - dvclive/DecisionTree/metrics.json
    plots:
    - dvclive/DecisionTree/plots

  test_CatBoost:
    cmd: python src/test_models/test_CB.py
    deps:
    - data/EDA_processed/test_data.csv
    - models/CatBoost.cbm
    - src/test_models/test_CB.py
    params:
    - config/parameters.yaml:
      - base
      - models.CatBoost
    metrics:
    - dvclive/CatBoost/metrics.json
    plots:
    - dvclive/CatBoost/plots

  test_XGBoost:
    cmd: python src/test_models/test_XGB.py
    deps:
    - data/EDA_processed/test_data.csv
    - models/XGBoost.json
    - src/test_models/test_XGB.py
    params:
    - config/parameters.yaml:
      - base
      - models.XGBoost
    metrics:
    - dvclive/XGBoost/metrics.json
    plots:
    - dvclive/XGBoost/plots

  test_DenseNeuralNetwork:
    cmd: python src/test_models/test_DNN.py
    deps:
    - data/EDA_processed/test_data.csv
    - models/DenseNeuralNetwork.keras
    - src/test_models/test_DNN.py
    params:
    - config/parameters.yaml:
      - base
      - models.DenseNeuralNetwork
    metrics:
    - dvclive/DenseNeuralNetwork/metrics.json
    plots:
    - dvclive/DenseNeuralNetwork/plots
metrics:
- dvclive/LinearRegression/metrics.json
- dvclive/DecisionTree/metrics.json
- dvclive/CatBoost/metrics.json
- dvclive/XGBoost/metrics.json
- dvclive/DenseNeuralNetwork/metrics.json
- dvclive/LinearRegression/metrics.json
- dvclive/DecisionTree/metrics.json
- dvclive/CatBoost/metrics.json
- dvclive/XGBoost/metrics.json
- dvclive/DenseNeuralNetwork/metrics.json
plots:
- dvclive/LinearRegression/plots/metrics:
    x: step
- dvclive/DecisionTree/plots/metrics:
    x: step
- dvclive/CatBoost/plots/metrics:
    x: step
- dvclive/XGBoost/plots/metrics:
    x: step
- dvclive/DenseNeuralNetwork/plots/metrics:
    x: step
- dvclive/LinearRegression/plots/metrics:
    x: step
- dvclive/DecisionTree/plots/metrics:
    x: step
- dvclive/CatBoost/plots/metrics:
    x: step
- dvclive/XGBoost/plots/metrics:
    x: step
- dvclive/DenseNeuralNetwork/plots/metrics:
    x: step
artifacts:
  LinearRegression_metrics:
    path: reports/metrics/LinearRegression_metrics.json
    type: metrics
  CatBoost_metrics:
    path: reports/metrics/CatBoost_metrics.json
    type: metrics
  XGBoost_metrics:
    path: reports/metrics/XGBoost_metrics.json
    type: metrics
  DenseNeuralNetwork_metrics:
    path: reports/metrics/DenseNeuralNetwork_metrics.json
    type: metrics
