base:
  random_state: 42
  test_size: 0.2
  val_size: 0.25                           # 25% от 80% = 20%
  root_project_dir: C:/ML_Labs/LB1_2_ML_Yakushev

data:
  dataset_csv: data/raw/life_expectancy_data.csv
  target: 'Life expectancy'

  new_dataset_path: data/EDA_processed/life_expectancy_data_processed.csv
  dataset_x_path: data/EDA_processed/data_x.npy
  dataset_y_path: data/EDA_processed/data_y.npy

  train_path: data/EDA_processed/train_data.csv
  val_path: data/EDA_processed/val_data.csv
  test_path: data/EDA_processed/test_data.csv

reports:
  coeffs_path: reports/
  metrics_path: reports/metrics/
  images_path: reports/images/
  dvclive_path: dvclive/
  optuna_params_path: reports/optuna_params/

models:
  optuna:
    n_trials: 50
    cv_folds: 3

  models_path: models/

  LinearRegression:
    fit_intercept: True                    # Наличие или отсутствие свободного члена в модели
    positive: False                        # При True только положительные коэффициенты в модели
    tol: 8.691979324081625e-07             # Допустимость критериев остановки

  DecisionTree:
    random_state: 42                       # Управляет случайностью оценки
    max_depth: 46                          # Максимальная глубина дерева
    min_samples_split: 3                   # Минимальное количество выборок, необходимое для разделения внутреннего узла
    min_samples_leaf: 2                    # Минимальное число объектов в листе
    max_features: 11                       # Число признаков для построения одного дерева
    ccp_alpha: 1.6148807499211317e-06      # Параметр сложности, используемый для обрезки по минимальной стоимости-сложности
    criterion: friedman_mse                # Функция для оценки качества разделения
    splitter: random                       # Стратегия, используемая для выбора способа разделения в каждом узле

  CatBoost:
    iterations: 775                        # Максимальное количество построенных деревьев
    learning_rate: 0.03251619490857449     # Скорость обучения (шаг градиента)
    depth: 10                              # Глубина дерева
    loss_function: RMSE                    # Метрика , используемая в процессе обучения
    grow_policy: Lossguide                 # Определяет, как будет применяться жадный алгоритм поиска

  XGBoost:
    n_estimators: 610                      # Количество деревьев
    max_depth: 14                          # Максимальная глубина дерева
    learning_rate: 0.060040896394708304    # Скорость обучения (шаг градиентного спуска)
    min_child_weight: 15                   # Минимальная сумма весов (или количество образцов) в листе

  DenseNeuralNetwork:
    dataset_params:
      validation_split: 0.2                # Доля обучающей выборки, выделяемая для валидации
      random_state: 42                     # Фиксация случайности при разбиении данных
    model_params:
      dropout_rate: 0.0038113471432177325  # Вероятность "выключения" нейрона в слоях Dropout
      n_layers: 5                          # Количество скрытых полносвязных слоёв в сети
      preout_neurons: 32                   # Базовое количество нейронов для расчёта размерности слоёв.
      learning_rate: 0.004761536180063235  # Скорость обучения оптимизатора Adam.
      activation: relu                     # Функция активации для скрытых слоёв
    train_params:
      epochs: 90                           # Количество полных проходов всего обучающего набора через сеть
      verbose: 1                           # Вывод метрик